services:
  localstack:
    image: localstack/localstack:3.7.2
    container_name: localstacks3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    networks:
      - app-network
    volumes:
      - "./dev/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh" # 初期化スクリプト
      - "./dev/users.json:/docker-entrypoint-initaws.d/users.json" # 初期データ
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-localstack-sample-app
    environment:
      - AWS_ENDPOINT_URL=http://localstacks3:4566
      - AWS_REGION=ap-northeast-1
      - AWS_S3_BUCKET=test-bucket
      - AWS_S3_KEY=users.json
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    networks:
      - app-network
    depends_on:
      localstack:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
